### ISSUE TITLE
Creating a Folder

### ISSUE THREAD

**Issue by lorebini** [toybreaker/binocle#2]
Ok, I can open a new project by editing this file:

binocle/_data/works.csv 

in fact I added 'studiobinocle' right now.
What I can't do is to add a folder named 'studiobinocle' in here:

binocle/works/

should be easy but I failed...

HELP!

**Comment by lorebini** [comment]
Ok,
very easy, google helped me with that:

On github you can do this:
go to the folder inside which you want to create another folder.
click on New file.
on the text field for the file name, first write the folder name you want to create.
then type / , this creates a folder.
you can add more folders similarly.

Stille the project title doesn't link to the project but to:

http://binocle.it/?ref=pnf

busy with that at the moment...

**Comment by lorebini** [comment]
Ok. Solved.
Guess was just an 'empty cash' situation ;)
No just upload the images when you have time man!
K

**Comment by toybreaker** [comment]
**cool** that you find how by yourself man, 
regarding the images they are online, 
reworked to meet the higher standard requested so the whites are not burned!

**Comment by lorebini** [comment]
si, mi sentivo troppo sfigato a non riuscire a creare un cazzo di folder, ahah!

**Comment by toybreaker** [comment]
assai figo che hai creato un issue e hai spiegato tutto bene compresa la
soluzione come fanno tutti i developer su github. congratulations very
Geek!👍🤘😎
