### ISSUE TITLE
CHANGE PIC HOMEPAGE

### ISSUE THREAD

**Issue by lorebini** [toybreaker/binocle#20]
non so come cambiare immagine home. Provato a caricare nuova immagine nelle varie dimensioni ma mi sa che mi manca un passaggio... Imparerò...

**Comment by toybreaker** [comment]
magari ci do un occhiata io, dove hai l'immagine nuova?

**Comment by toybreaker** [comment]
ops mi ero dimenticato di questo...

**Comment by toybreaker** [comment]
Done!..
updated home picture + general clean up of old code not needed anymore...
